# Generated by Django 5.0.3 on 2024-03-14 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_rename_description_course_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecture',
            new_name='VideoModel',
        ),
    ]
