# Generated by Django 5.0.3 on 2024-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0006_videomodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='pdf',
            field=models.FileField(default='', upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video',
            field=models.FileField(default='', upload_to='video'),
        ),
    ]
