# Generated by Django 5.0.3 on 2024-03-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0007_videomodel_pdf_videomodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='pdf',
        ),
    ]
