# Generated by Django 5.0.3 on 2024-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0008_remove_videomodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
    ]
