# Generated by Django 5.0.3 on 2024-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0010_alter_videomodel_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=10)),
                ('image_data', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
