# Generated by Django 5.0.3 on 2024-03-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0017_videomodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='like',
        ),
    ]
