# Generated by Django 5.0.3 on 2024-03-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0018_remove_videomodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tutorapp.videomodel'),
        ),
    ]
