# Generated by Django 5.0.3 on 2024-03-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0019_alter_likevideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tutorapp.videomodel'),
        ),
    ]
