# Generated by Django 5.0.3 on 2024-03-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0021_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.ratings'),
        ),
    ]
