# Generated by Django 5.0.3 on 2024-03-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0022_videomodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
