# Generated by Django 5.0.3 on 2024-03-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0025_alter_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.ratings'),
        ),
    ]
