# Generated by Django 5.0.3 on 2024-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0027_ratevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
