# Generated by Django 5.0.3 on 2024-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0028_remove_videomodel_ratings_delete_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratevideo',
            name='user_rating',
            field=models.IntegerField(),
        ),
    ]
