# Generated by Django 5.0.3 on 2024-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0029_alter_ratevideo_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratevideo',
            name='user_rating',
            field=models.IntegerField(null=True),
        ),
    ]
