# Generated by Django 5.0.3 on 2024-03-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0031_commenttutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratevideo',
            name='user_rating',
            field=models.IntegerField(default=1),
        ),
    ]
