# Generated by Django 5.0.3 on 2024-03-31 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0033_alter_videomodel_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
