# Generated by Django 5.0.3 on 2024-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0036_alter_order_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartvideo',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
