# Generated by Django 5.0.3 on 2024-04-10 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0037_cartvideo_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartvideo',
            name='carted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
