# Generated by Django 5.0.3 on 2024-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0038_cartvideo_carted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='free_course',
            field=models.BooleanField(default=True),
        ),
    ]
