# Generated by Django 5.0.3 on 2024-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0039_videomodel_free_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
